name: fodder_tools
description: Tools for (original) PC Cannon Fodder (sprite extraction, archive parsing, etc.)
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ^3.41.2

dependencies:
  args: ^2.7.0
  fodder_core:
    path: ../fodder_core
  image: ^4.8.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.29.0
  very_good_analysis: ^10.2.0

executables:
  extract: extract
  maps: maps
  sprites: sprites
  audio: audio
