name: fodder_workspace
publish_to: none

workspace:
  - apps/fodder_game
  - packages/fodder_tools

environment:
  sdk: ^3.11.0

dev_dependencies:
  melos: ^7.4.0

melos:
  repository: https://github.com/bramp/fodder

  ide:
    intellij: false

  scripts:
    analyze:
      run: melos exec -c 1 -- "flutter analyze"
      description: Run `flutter analyze` in all packages.
    test:
      run: melos exec -c 1 -- "flutter test"
      description: Run `flutter test` in all packages.
    format:
      run: melos exec -c 1 -- "dart format ."
      description: Run `dart format` in all packages.
