// ignore_for_file: avoid_print, CLI tool uses print for user output.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:args/args.dart';
import 'package:path/path.dart' as p;

// The archive library lives in a sibling tool directory and is imported
// via a relative path since neither package has its own pubspec.yaml.
// ignore: avoid_relative_lib_imports
import '../archive/lib/dat_reader.dart';
import 'lib/atlas_writer.dart';
import 'lib/image_decoder.dart';
import 'lib/palette.dart';
import 'lib/png_writer.dart';
import 'lib/sprite_frame.dart';

// ---------------------------------------------------------------------------
// Palette metadata tables
// ---------------------------------------------------------------------------

/// Known 4-bit sprite-sheet files and their palette metadata.
///
/// Format: filename → list of (paletteOffset, colorCount, basePaletteIndex).
/// All use a 160-byte pitch (320 pixel width).
const _spriteSheets4Bit = <String, List<_PaletteSpec>>{
  'pstuff.dat': [_PaletteSpec(0xA000, 0x10, 0xF0)],
  'font.dat': [_PaletteSpec(0xA000, 0x10, 0xD0)],
  'hillbits.dat': [_PaletteSpec(0x6900, 0x10, 0xB0)],
  'rankfont.dat': [_PaletteSpec(0xA000, 0x80, 0x40)],
};

/// Known 4-bit in-game sprite-sheet files (terrain-specific).
///
/// army.dat files use palette index 0xA0.
const _armySheets = <String, _PaletteSpec>{
  'junarmy.dat': _PaletteSpec(0xD200, 0x10, 0xA0),
  'desarmy.dat': _PaletteSpec(0xD200, 0x10, 0xA0),
  'icearmy.dat': _PaletteSpec(0xD200, 0x10, 0xA0),
  'morarmy.dat': _PaletteSpec(0xD200, 0x10, 0xA0),
  'intarmy.dat': _PaletteSpec(0xD200, 0x10, 0xA0),
};

/// Copt (helicopter) sheets have two palette regions.
const _coptSheets = <String, List<_PaletteSpec>>{
  'juncopt.dat': [
    _PaletteSpec(0xD360, 0x10, 0x90),
    _PaletteSpec(0xD2A0, 0x40, 0xB0),
  ],
  'descopt.dat': [
    _PaletteSpec(0xD360, 0x10, 0x90),
    _PaletteSpec(0xD2A0, 0x40, 0xB0),
  ],
  'icecopt.dat': [
    _PaletteSpec(0xD360, 0x10, 0x90),
    _PaletteSpec(0xD2A0, 0x40, 0xB0),
  ],
  'morcopt.dat': [
    _PaletteSpec(0xD360, 0x10, 0x90),
    _PaletteSpec(0xD2A0, 0x40, 0xB0),
  ],
  'intcopt.dat': [
    _PaletteSpec(0xD360, 0x10, 0x90),
    _PaletteSpec(0xD2A0, 0x40, 0xB0),
  ],
};

/// Known 8-bit linear images with embedded palettes.
const _linear8Bit = <String, _PaletteSpec>{
  'hill.dat': _PaletteSpec(0xFA00, 0x50, 0x00),
  'morphbig.dat': _PaletteSpec(0xFA00, 0x40, 0x00),
  'cftitle.dat': _PaletteSpec(0xFA00, 0x50, 0x00),
};

/// Tile base-block files (palette at 0xFA00, 128 colours).
const _tileBaseBlocks = <String>{
  'junbase.blk',
  'desbase.blk',
  'icebase.blk',
  'morbase.blk',
  'intbase.blk',
};

/// Tile sub-block files (reuse the palette from their matching base).
const _tileSubBlocks = <String>{
  'junsub0.blk',
  'dessub0.blk',
  'icesub0.blk',
  'morsub0.blk',
  'intsub0.blk',
  'junsub1.blk',
};

class _PaletteSpec {
  const _PaletteSpec(this.offset, this.count, this.startIndex);
  final int offset;
  final int count;
  final int startIndex;
}

// ---------------------------------------------------------------------------
// CLI entry-point
// ---------------------------------------------------------------------------

void main(List<String> arguments) {
  final parser = ArgParser()
    ..addOption(
      'dat',
      abbr: 'd',
      help: 'Path to CF_ENG.DAT archive.',
      mandatory: true,
    )
    ..addOption(
      'output',
      abbr: 'o',
      help: 'Output directory for PNGs.',
      defaultsTo: 'output',
    )
    ..addOption(
      'input',
      abbr: 'i',
      help:
          'Path to pre-extracted directory '
          '(use instead of --dat).',
    )
    ..addOption(
      'sprite-data',
      abbr: 's',
      help:
          'Directory containing exported sprite metadata JSONs '
          '(generated by export_sprite_data.dart).',
    )
    ..addFlag(
      'sprites',
      help: 'Extract individual sprites (requires --sprite-data).',
      negatable: false,
    )
    ..addFlag(
      'help',
      abbr: 'h',
      negatable: false,
      help: 'Show usage.',
    );

  final args = parser.parse(arguments);
  if (args['help'] as bool) {
    print('Usage: dart run tool/sprites/main.dart [options]');
    print(parser.usage);
    return;
  }

  final outputDir = Directory(args['output'] as String);
  if (!outputDir.existsSync()) {
    outputDir.createSync(recursive: true);
  }

  // Resolve file access — archive or pre-extracted directory.
  // TODO(bramp): Instead of these two closures, we could define an abstract
  // ArchiveProvider class with two implementations.
  final Uint8List Function(String) getFile;
  final bool Function(String) hasFile;

  final extractedPath = args['input'] as String?;
  if (extractedPath != null) {
    final dir = Directory(extractedPath);
    if (!dir.existsSync()) {
      print('Error: directory not found: $extractedPath');
      return;
    }
    getFile = (f) => File(p.join(dir.path, f)).readAsBytesSync();
    hasFile = (f) => File(p.join(dir.path, f)).existsSync();
  } else {
    final datFile = File(args['dat'] as String);
    if (!datFile.existsSync()) {
      print('Error: DAT not found: ${datFile.path}');
      return;
    }
    final reader = DatReader(datFile)..read();
    final entryMap = {
      for (final e in reader.entries) e.filename: e,
    };
    getFile = (f) => reader.getFileBytes(entryMap[f]!);
    hasFile = entryMap.containsKey;
  }

  var exported = 0;

  // --- 4-bit sprite sheets ---
  for (final entry in _spriteSheets4Bit.entries) {
    if (!hasFile(entry.key)) continue;
    exported += _export4Bit(
      entry.key,
      getFile(entry.key),
      entry.value,
      outputDir,
      label: '4-bit',
    );
  }

  // --- Army sheets (4-bit) ---
  for (final entry in _armySheets.entries) {
    if (!hasFile(entry.key)) continue;
    exported += _export4Bit(
      entry.key,
      getFile(entry.key),
      [entry.value],
      outputDir,
      label: '4-bit army',
    );
  }

  // --- Copt sheets (4-bit, dual palette) ---
  for (final entry in _coptSheets.entries) {
    if (!hasFile(entry.key)) continue;
    exported += _export4Bit(
      entry.key,
      getFile(entry.key),
      entry.value,
      outputDir,
      label: '4-bit copt',
    );
  }

  // --- 8-bit linear images ---
  for (final entry in _linear8Bit.entries) {
    if (!hasFile(entry.key)) continue;
    exported += _export8BitLinear(
      entry.key,
      getFile(entry.key),
      entry.value,
      outputDir,
    );
  }

  // --- Tile base blocks ---
  for (final filename in _tileBaseBlocks) {
    if (!hasFile(filename)) continue;
    exported += _exportTile(
      filename,
      getFile(filename),
      null,
      outputDir,
      label: 'tile base',
    );
  }

  // --- Tile sub blocks ---
  for (final filename in _tileSubBlocks) {
    if (!hasFile(filename)) continue;
    final prefix = filename.substring(0, 3);
    final baseFilename = '${prefix}base.blk';
    if (!hasFile(baseFilename)) continue;
    exported += _exportTile(
      filename,
      getFile(filename),
      getFile(baseFilename),
      outputDir,
      label: 'tile sub',
    );
  }

  print('Exported $exported images to ${outputDir.path}');

  // --- Individual sprite extraction ---
  if (args['sprites'] as bool) {
    final spriteDataPath = args['sprite-data'] as String?;
    if (spriteDataPath == null) {
      print('Error: --sprite-data is required when using --sprites.');
      return;
    }
    final systemType = FileSystemEntity.typeSync(spriteDataPath).toString();
    if (!systemType.contains('file') && !systemType.contains('directory')) {
      print('Error: --sprite-data path not found: $spriteDataPath');
      return;
    }

    _exportSpriteAtlases(
      spriteDataPath: spriteDataPath,
      hasFile: hasFile,
      outputDir: outputDir,
    );
  }
}

// ---------------------------------------------------------------------------
// Export helpers
// ---------------------------------------------------------------------------

int _export4Bit(
  String filename,
  Uint8List data,
  List<_PaletteSpec> specs,
  Directory outputDir, {
  required String label,
}) {
  final palette = Palette();
  for (final spec in specs) {
    palette.load(
      data: data,
      offset: spec.offset,
      count: spec.count,
      startIndex: spec.startIndex,
    );
  }
  final firstSpec = specs.first;
  final pixels = decode4Bit(
    data: data,
    palette: palette,
    basePaletteIndex: firstSpec.startIndex,
    paletteOffset: firstSpec.offset,
  );
  const width = 320;
  final height = pixels.length ~/ width;
  // TODO(bramp): The follow encode + save can be refactored into a function
  // since it's repeated in all export types.
  final png = encodePng(
    pixels: pixels,
    width: width,
    height: height,
  );
  final outPath = p.join(
    outputDir.path,
    '${p.basenameWithoutExtension(filename)}.png',
  );
  File(outPath).writeAsBytesSync(png);
  print('  $outPath (${width}x$height, $label)');
  return 1;
}

int _export8BitLinear(
  String filename,
  Uint8List data,
  _PaletteSpec spec,
  Directory outputDir,
) {
  final palette = Palette()
    ..load(
      data: data,
      offset: spec.offset,
      count: spec.count,
      startIndex: spec.startIndex,
    );
  final pixelCount = spec.offset;
  final pixels = decode8Bit(
    data: data,
    palette: palette,
    pixelCount: pixelCount,
  );
  const width = 320;
  final height = pixelCount ~/ width;
  final png = encodePng(
    pixels: pixels,
    width: width,
    height: height,
  );
  final outPath = p.join(
    outputDir.path,
    '${p.basenameWithoutExtension(filename)}.png',
  );
  File(outPath).writeAsBytesSync(png);
  print('  $outPath (${width}x$height, 8-bit linear)');
  return 1;
}

int _exportTile(
  String filename,
  Uint8List data,
  Uint8List? basePaletteData,
  Directory outputDir, {
  required String label,
}) {
  final palSrc = basePaletteData ?? data;
  final palette = Palette()..load(data: palSrc, offset: 0xFA00, count: 0x80);
  const pixelCount = 0xFA00;
  final pixels = decode8Bit(
    data: data,
    palette: palette,
    pixelCount: pixelCount,
  );
  const width = 320;
  const height = pixelCount ~/ width;
  final png = encodePng(
    pixels: pixels,
    width: width,
    height: height,
  );
  final outPath = p.join(
    outputDir.path,
    '${p.basenameWithoutExtension(filename)}.png',
  );
  File(outPath).writeAsBytesSync(png);
  print('  $outPath (${width}x$height, $label)');
  return 1;
}

// ---------------------------------------------------------------------------
// Sprite atlas generation (TexturePacker JSON Hash format)
// ---------------------------------------------------------------------------

/// Maps [GfxType] values to their source .dat filename and palette specs.
///
/// Terrain-specific types (eGFX_IN_GAME, eGFX_IN_GAME2) are handled
/// dynamically since the filename depends on the active tileset.
const _gfxTypeFiles = <GfxType, _GfxFileSpec>{
  GfxType.font: _GfxFileSpec('font.dat', [_PaletteSpec(0xA000, 0x10, 0xD0)]),
  GfxType.pstuff: _GfxFileSpec(
    'pstuff.dat',
    [_PaletteSpec(0xA000, 0x10, 0xF0)],
  ),
  GfxType.hill: _GfxFileSpec(
    'hillbits.dat',
    [_PaletteSpec(0x6900, 0x10, 0xB0)],
  ),
  GfxType.recruit: _GfxFileSpec(
    'hillbits.dat',
    [_PaletteSpec(0x6900, 0x10, 0xB0)],
  ),
  GfxType.briefing: _GfxFileSpec(
    'pstuff.dat',
    [_PaletteSpec(0xA000, 0x10, 0xF0)],
  ),
  GfxType.rankFont: _GfxFileSpec(
    'rankfont.dat',
    [_PaletteSpec(0xA000, 0x80, 0x40)],
  ),
  GfxType.service: _GfxFileSpec(
    'morphbig.dat',
    [_PaletteSpec(0xFA00, 0x40, 0x00)],
  ),
};

class _GfxFileSpec {
  const _GfxFileSpec(this.filename, this.paletteSpecs);
  final String filename;
  final List<_PaletteSpec> paletteSpecs;
}

/// Generates TexturePacker JSON atlas files alongside the already-exported
/// sprite sheet PNGs.
///
/// For each source .dat file referenced by sprites, a companion `.json` is
/// written next to the existing `.png`. Sprite names follow the convention
/// `{SpriteSheetType}/{groupHex}_{frameIndex}`.
void _exportSpriteAtlases({
  required String spriteDataPath,
  required bool Function(String) hasFile,
  required Directory outputDir,
}) {
  final List<SpriteSheetType> sheetTypes;

  if (FileSystemEntity.isDirectorySync(spriteDataPath)) {
    print('\nLoading sprite data from JSON files in $spriteDataPath...');
    sheetTypes = [];
    final dir = Directory(spriteDataPath);
    for (final file in dir.listSync().whereType<File>()) {
      if (!p.basename(file.path).endsWith('.json')) continue;
      if (!p.basename(file.path).startsWith('sprite_sheet_')) continue;

      final nameMatch = RegExp(
        r'sprite_sheet_(.+)\.json',
      ).firstMatch(p.basename(file.path));
      if (nameMatch == null) continue;

      final name = nameMatch.group(1)!;
      final json = jsonDecode(file.readAsStringSync()) as List<dynamic>;
      sheetTypes.add(SpriteSheetType.fromJson(name, json));
    }
  } else {
    print(
      '\nError: --sprite-data must be a directory containing '
      'sprite_sheet_*.json files.',
    );
    print('Run tool/sprites/export_sprite_data.dart first.');
    return;
  }

  if (sheetTypes.isEmpty) {
    print('No sprite sheet metadata found in $spriteDataPath');
    return;
  }

  print('Found ${sheetTypes.length} sprite sheet types:');
  for (final st in sheetTypes) {
    var totalFrames = 0;
    for (final group in st.entries) {
      totalFrames += group.length;
    }
    print(
      '  ${st.name}: ${st.entries.length} groups, $totalFrames total frames',
    );
  }

  // Resolve GfxType → actual filename (for terrain-specific types, pick the
  // first available file).
  final gfxTypeFilename = <GfxType, String>{};
  for (final entry in _gfxTypeFiles.entries) {
    if (hasFile(entry.value.filename)) {
      gfxTypeFilename[entry.key] = entry.value.filename;
    }
  }

  // Pick first available army/copt filename for terrain-specific types.
  for (final entry in _armySheets.entries) {
    if (hasFile(entry.key)) {
      gfxTypeFilename[GfxType.inGame] = entry.key;
      break;
    }
  }
  for (final entry in _coptSheets.entries) {
    if (hasFile(entry.key)) {
      gfxTypeFilename[GfxType.inGame2] = entry.key;
      break;
    }
  }

  // Collect atlas entries grouped by source .dat filename.
  // key = .dat filenameList, value = list of atlas entries.
  final atlasEntries = <String, List<AtlasEntry>>{};

  // Also track image heights per filename.
  final imageHeights = <String, int>{};

  // Build a map of GfxType to ALL files that use it.
  final gfxTypeToFiles = <GfxType, List<String>>{};
  for (final entry in _gfxTypeFiles.entries) {
    if (hasFile(entry.value.filename)) {
      gfxTypeToFiles.putIfAbsent(entry.key, () => []).add(entry.value.filename);
    }
  }
  for (final entry in _armySheets.entries) {
    if (hasFile(entry.key)) {
      gfxTypeToFiles.putIfAbsent(GfxType.inGame, () => []).add(entry.key);
    }
  }
  for (final entry in _coptSheets.entries) {
    if (hasFile(entry.key)) {
      gfxTypeToFiles.putIfAbsent(GfxType.inGame2, () => []).add(entry.key);
    }
  }

  for (final sheetType in sheetTypes) {
    for (var groupIdx = 0; groupIdx < sheetType.entries.length; groupIdx++) {
      final group = sheetType.entries[groupIdx];
      for (var frameIdx = 0; frameIdx < group.length; frameIdx++) {
        final frame = group[frameIdx];

        if (frame.width <= 0 || frame.height <= 0) continue;

        final filenames = gfxTypeToFiles[frame.gfxType];
        if (filenames == null) continue;

        for (final filename in filenames) {
          final groupHex = groupIdx.toRadixString(16).padLeft(2, '0');
          final name = '${sheetType.name}/${groupHex}_$frameIdx';

          final x = frame.pixelX();
          final y = frame.pixelY();

          atlasEntries
              .putIfAbsent(filename, () => [])
              .add(
                AtlasEntry(
                  name: name,
                  x: x,
                  y: y,
                  width: frame.width,
                  height: frame.height,
                ),
              );

          // Track maximum required height for this image.
          final bottomEdge = y + frame.height;
          final prev = imageHeights[filename] ?? 0;
          if (bottomEdge > prev) {
            imageHeights[filename] = bottomEdge;
          }
        }
      }
    }
  }

  // Write one TexturePacker JSON per source file.
  var atlasCount = 0;
  for (final entry in atlasEntries.entries) {
    final datFilename = entry.key;
    final entries = entry.value;
    final pngFilename = '${p.basenameWithoutExtension(datFilename)}.png';
    final jsonFilename = '${p.basenameWithoutExtension(datFilename)}.json';

    const imageWidth = 320;
    final imageHeight = imageHeights[datFilename] ?? 0;

    final json = generateAtlasJson(
      imageFilename: pngFilename,
      imageWidth: imageWidth,
      imageHeight: imageHeight,
      entries: entries,
    );

    final outPath = p.join(outputDir.path, jsonFilename);
    File(outPath).writeAsStringSync(json);
    print('  $outPath (${entries.length} sprites)');
    atlasCount++;
  }

  print('Generated $atlasCount atlas JSON files in ${outputDir.path}');
}
