// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa9_qeCHNh_UyI8wHnk_tEdH_jk0Pr99s',
    appId: '1:900023187428:web:819cd014a946ff90f839f1',
    messagingSenderId: '900023187428',
    projectId: 'fodder-bramp-net',
    authDomain: 'fodder-bramp-net.firebaseapp.com',
    storageBucket: 'fodder-bramp-net.firebasestorage.app',
    measurementId: 'G-F7WF7HFSJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqz1ENaleYNYJgSk8SEFjwJ87hnQ1mAl0',
    appId: '1:900023187428:android:0ad0e42cd7c612fbf839f1',
    messagingSenderId: '900023187428',
    projectId: 'fodder-bramp-net',
    storageBucket: 'fodder-bramp-net.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgm9uEDn0LwdKKTmFfd02lv5qKUgx1h8',
    appId: '1:900023187428:ios:5113842402e8d162f839f1',
    messagingSenderId: '900023187428',
    projectId: 'fodder-bramp-net',
    storageBucket: 'fodder-bramp-net.firebasestorage.app',
    iosBundleId: 'net.bramp.fodder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFgm9uEDn0LwdKKTmFfd02lv5qKUgx1h8',
    appId: '1:900023187428:ios:5113842402e8d162f839f1',
    messagingSenderId: '900023187428',
    projectId: 'fodder-bramp-net',
    storageBucket: 'fodder-bramp-net.firebasestorage.app',
    iosBundleId: 'net.bramp.fodder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa9_qeCHNh_UyI8wHnk_tEdH_jk0Pr99s',
    appId: '1:900023187428:web:447bd37c66655a95f839f1',
    messagingSenderId: '900023187428',
    projectId: 'fodder-bramp-net',
    authDomain: 'fodder-bramp-net.firebaseapp.com',
    storageBucket: 'fodder-bramp-net.firebasestorage.app',
    measurementId: 'G-TL1FP7MY92',
  );
}
