import 'dart:convert';
import 'dart:ui';

import 'package:flame/cache.dart';
import 'package:flame/components.dart';
import 'package:flutter/services.dart';

/// Sprite scale factor (original 16 px tiles rendered at 32 px).
const _spriteScale = 2.0;

/// Mapping from TMX object names to copt atlas frame keys.
///
/// The TMX `Sprites` layer gives each object a human-readable `name`
/// (derived from the `SpriteType` enum in `fodder_tools`). The copt atlas
/// (`juncopt.json` etc.) names frames using a `env_` prefix generated by
/// `inGameGroupNames` in `sprite_names.dart`.
///
/// | TMX name       | Atlas frame                  |
/// |----------------|------------------------------|
/// | `shrub`        | `ingame/env_shrub_0`         |
/// | `tree`         | `ingame/env_tree_0`          |
/// | `buildingRoof` | `ingame/env_building_roof_0` |
/// | `snowman`      | `ingame/env_snowman_0`       |
/// | `shrub2`       | `ingame/env_shrub2_0`        |
const environmentSpriteFrames = <String, String>{
  'shrub': 'ingame/env_shrub_0',
  'tree': 'ingame/env_tree_0',
  'buildingRoof': 'ingame/env_building_roof_0',
  'snowman': 'ingame/env_snowman_0',
  'shrub2': 'ingame/env_shrub2_0',
};

/// Set of TMX object names that are environment decoration sprites.
const environmentSpriteNames = {
  'shrub',
  'tree',
  'buildingRoof',
  'snowman',
  'shrub2',
};

/// A static environment decoration rendered from the copt sprite atlas.
///
/// These sprites (shrubs, tree tops, building roofs, etc.) are defined in
/// the TMX `Sprites` object layer alongside soldier spawn points. The
/// original engine draws them as normal sprites sorted by Y position, so
/// that soldiers walking below the sprite's anchor appear behind the
/// decoration — creating the illusion of walking under tree canopies.
///
/// We use `priority: 15` (above soldiers at 10, below debug overlay at 20)
/// so environment sprites always render on top of soldiers, matching the
/// original game's visual behaviour for tree-top / canopy overlays.
class EnvironmentSprite extends SpriteComponent {
  EnvironmentSprite({
    required super.sprite,
    required super.position,
    required super.size,
  }) : super(
         anchor: Anchor.bottomLeft,
         priority: 15,
       );

  /// Creates an [EnvironmentSprite] for the given spawn [name] from the
  /// copt atlas.
  ///
  /// The [name] is the TMX object name (e.g. `"shrub"`, `"tree"`).
  /// Returns `null` if the name is not a known environment sprite.
  static Future<EnvironmentSprite?> fromSpawnData({
    required String name,
    required Vector2 position,
    required Image atlasImage,
    required Map<String, dynamic> framesMap,
  }) async {
    final frameName = environmentSpriteFrames[name];
    if (frameName == null) return null;

    final frameData = framesMap[frameName] as Map<String, dynamic>?;
    if (frameData == null) return null;

    final frame = frameData['frame'] as Map<String, dynamic>;
    final sprite = Sprite(
      atlasImage,
      srcPosition: Vector2(
        (frame['x'] as num).toDouble(),
        (frame['y'] as num).toDouble(),
      ),
      srcSize: Vector2(
        (frame['w'] as num).toDouble(),
        (frame['h'] as num).toDouble(),
      ),
    );

    return EnvironmentSprite(
      sprite: sprite,
      position: position,
      size: sprite.srcSize * _spriteScale,
    );
  }

  /// Loads the copt atlas frames map for reuse across multiple sprites.
  ///
  /// Call once, then pass the result to [fromSpawnData] for each sprite.
  static Future<({Image image, Map<String, dynamic> framesMap})> loadAtlas({
    required String prefix,
    required String atlasJsonFile,
    required String imageFile,
  }) async {
    final images = Images(prefix: prefix);
    final image = await images.load(imageFile);

    final jsonString = await rootBundle.loadString('$prefix$atlasJsonFile');
    final jsonData = json.decode(jsonString) as Map<String, dynamic>;
    final framesMap = jsonData['frames'] as Map<String, dynamic>;

    return (image: image, framesMap: framesMap);
  }
}
